sudo: false
language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
    - pip install 'travis-cargo>=0.1.0,<0.2.0' --user
    - pip install 'CppHeaderParser>=2.7.2,<3.0.0' --user
    - travis-cargo --only nightly install clippy
script:
    - travis-cargo build
    - ./on-nightly cargo clippy --all
    - travis-cargo test
    - travis-cargo --only stable doc
env:
    global:
        - RUST_BACKTRACE=1
        - TRAVIS_CARGO_NIGHTLY_FEATURE=""
